version: "3"

services:
  backend:
    build: .
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGO_URI}
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test
    volumes:
      - db-data:/data/db

volumes:
  db-data:
